# Generated by Django 5.1.15 on 2026-02-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satorbit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='question',
            new_name='satellite',
        ),
        migrations.AddField(
            model_name='satellite',
            name='x_coord',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='satellite',
            name='y_coord',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='satellite',
            name='z_coord',
            field=models.FloatField(default=0.0),
        ),
    ]
